### ISSUE TITLE
Basic reproduction number in readme is incorrect

### ISSUE THREAD

**Issue by kdhansen** [metalcorebear/COVID-Agent-Based-Model#2]
It is stated in the readme that a negative basic reproduction number means that the epidemic is being extinguished. Usually, however, R_0 is positive but needs to be less 1 to extinguish the epidemic.

See: https://en.wikipedia.org/wiki/Basic_reproduction_number

**Comment by metalcorebear** [comment]
It definitely shouldn’t say negative Ro in the README file. Thank you for pointing that out (I’ll fix it).

MB

**Comment by DemetersSon83** [comment]
I've corrected the issue in the README file.
